/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the OverviewMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OverviewMetric{}

// OverviewMetric struct for OverviewMetric
type OverviewMetric struct {
	// String representing the object's type. Objects of the same type share the same value.
	Object string `json:"object"`
	// Id of the overview metric
	Id string `json:"id"`
	// Display name of the overview metric
	Name string `json:"name"`
	// Description of the overview metric
	Description string `json:"description"`
	// Unit of the overview metric
	Unit string `json:"unit"`
	// Length of time during which metric data is collected in ISO 8601 format. Zero period means metric data was collected now
	Period string `json:"period"`
	// Value of the overview metric
	Value float32 `json:"value"`
	// Last time the overview metric was updated in ms since epoch
	LastUpdatedAt NullableInt64 `json:"last_updated_at"`
	// Last time the overview metric was updated datetime in ISO 8601 format
	LastUpdatedAtIso8601 NullableTime `json:"last_updated_at_iso8601"`
}

type _OverviewMetric OverviewMetric

// NewOverviewMetric instantiates a new OverviewMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOverviewMetric(object string, id string, name string, description string, unit string, period string, value float32, lastUpdatedAt NullableInt64, lastUpdatedAtIso8601 NullableTime) *OverviewMetric {
	this := OverviewMetric{}
	this.Object = object
	this.Id = id
	this.Name = name
	this.Description = description
	this.Unit = unit
	this.Period = period
	this.Value = value
	this.LastUpdatedAt = lastUpdatedAt
	this.LastUpdatedAtIso8601 = lastUpdatedAtIso8601
	return &this
}

// NewOverviewMetricWithDefaults instantiates a new OverviewMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOverviewMetricWithDefaults() *OverviewMetric {
	this := OverviewMetric{}
	return &this
}

// GetObject returns the Object field value
func (o *OverviewMetric) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *OverviewMetric) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *OverviewMetric) SetObject(v string) {
	o.Object = v
}

// GetId returns the Id field value
func (o *OverviewMetric) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OverviewMetric) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OverviewMetric) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *OverviewMetric) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OverviewMetric) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OverviewMetric) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *OverviewMetric) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *OverviewMetric) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *OverviewMetric) SetDescription(v string) {
	o.Description = v
}

// GetUnit returns the Unit field value
func (o *OverviewMetric) GetUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
func (o *OverviewMetric) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unit, true
}

// SetUnit sets field value
func (o *OverviewMetric) SetUnit(v string) {
	o.Unit = v
}

// GetPeriod returns the Period field value
func (o *OverviewMetric) GetPeriod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Period
}

// GetPeriodOk returns a tuple with the Period field value
// and a boolean to check if the value has been set.
func (o *OverviewMetric) GetPeriodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Period, true
}

// SetPeriod sets field value
func (o *OverviewMetric) SetPeriod(v string) {
	o.Period = v
}

// GetValue returns the Value field value
func (o *OverviewMetric) GetValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *OverviewMetric) GetValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *OverviewMetric) SetValue(v float32) {
	o.Value = v
}

// GetLastUpdatedAt returns the LastUpdatedAt field value
// If the value is explicit nil, the zero value for int64 will be returned
func (o *OverviewMetric) GetLastUpdatedAt() int64 {
	if o == nil || o.LastUpdatedAt.Get() == nil {
		var ret int64
		return ret
	}

	return *o.LastUpdatedAt.Get()
}

// GetLastUpdatedAtOk returns a tuple with the LastUpdatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OverviewMetric) GetLastUpdatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdatedAt.Get(), o.LastUpdatedAt.IsSet()
}

// SetLastUpdatedAt sets field value
func (o *OverviewMetric) SetLastUpdatedAt(v int64) {
	o.LastUpdatedAt.Set(&v)
}

// GetLastUpdatedAtIso8601 returns the LastUpdatedAtIso8601 field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *OverviewMetric) GetLastUpdatedAtIso8601() time.Time {
	if o == nil || o.LastUpdatedAtIso8601.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastUpdatedAtIso8601.Get()
}

// GetLastUpdatedAtIso8601Ok returns a tuple with the LastUpdatedAtIso8601 field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OverviewMetric) GetLastUpdatedAtIso8601Ok() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdatedAtIso8601.Get(), o.LastUpdatedAtIso8601.IsSet()
}

// SetLastUpdatedAtIso8601 sets field value
func (o *OverviewMetric) SetLastUpdatedAtIso8601(v time.Time) {
	o.LastUpdatedAtIso8601.Set(&v)
}

func (o OverviewMetric) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OverviewMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["unit"] = o.Unit
	toSerialize["period"] = o.Period
	toSerialize["value"] = o.Value
	toSerialize["last_updated_at"] = o.LastUpdatedAt.Get()
	toSerialize["last_updated_at_iso8601"] = o.LastUpdatedAtIso8601.Get()
	return toSerialize, nil
}

func (o *OverviewMetric) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"id",
		"name",
		"description",
		"unit",
		"period",
		"value",
		"last_updated_at",
		"last_updated_at_iso8601",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOverviewMetric := _OverviewMetric{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOverviewMetric)

	if err != nil {
		return err
	}

	*o = OverviewMetric(varOverviewMetric)

	return err
}

type NullableOverviewMetric struct {
	value *OverviewMetric
	isSet bool
}

func (v NullableOverviewMetric) Get() *OverviewMetric {
	return v.value
}

func (v *NullableOverviewMetric) Set(val *OverviewMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableOverviewMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableOverviewMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOverviewMetric(val *OverviewMetric) *NullableOverviewMetric {
	return &NullableOverviewMetric{value: val, isSet: true}
}

func (v NullableOverviewMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOverviewMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


