/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomerAlias type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerAlias{}

// CustomerAlias struct for CustomerAlias
type CustomerAlias struct {
	// String representing the object's type. Objects of the same type share the same value.
	Object string `json:"object"`
	Id string `json:"id"`
	// The time when the alias was created
	CreatedAt int64 `json:"created_at"`
}

type _CustomerAlias CustomerAlias

// NewCustomerAlias instantiates a new CustomerAlias object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerAlias(object string, id string, createdAt int64) *CustomerAlias {
	this := CustomerAlias{}
	this.Object = object
	this.Id = id
	this.CreatedAt = createdAt
	return &this
}

// NewCustomerAliasWithDefaults instantiates a new CustomerAlias object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerAliasWithDefaults() *CustomerAlias {
	this := CustomerAlias{}
	return &this
}

// GetObject returns the Object field value
func (o *CustomerAlias) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *CustomerAlias) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *CustomerAlias) SetObject(v string) {
	o.Object = v
}

// GetId returns the Id field value
func (o *CustomerAlias) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CustomerAlias) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CustomerAlias) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CustomerAlias) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CustomerAlias) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CustomerAlias) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

func (o CustomerAlias) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerAlias) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["id"] = o.Id
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *CustomerAlias) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"id",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerAlias := _CustomerAlias{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomerAlias)

	if err != nil {
		return err
	}

	*o = CustomerAlias(varCustomerAlias)

	return err
}

type NullableCustomerAlias struct {
	value *CustomerAlias
	isSet bool
}

func (v NullableCustomerAlias) Get() *CustomerAlias {
	return v.value
}

func (v *NullableCustomerAlias) Set(val *CustomerAlias) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerAlias) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerAlias) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerAlias(val *CustomerAlias) *NullableCustomerAlias {
	return &NullableCustomerAlias{value: val, isSet: true}
}

func (v NullableCustomerAlias) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerAlias) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


