/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RCBillingAppCreateRcBilling type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RCBillingAppCreateRcBilling{}

// RCBillingAppCreateRcBilling Revenue Cat Billing Store type details
type RCBillingAppCreateRcBilling struct {
	// It needs to be connected to your RevenueCat account. It can be omitted if you only have a single Stripe account connected to your RevenueCat account.
	StripeAccountId NullableString `json:"stripe_account_id,omitempty"`
	// Shown in checkout, emails, and receipts sent to customers.
	AppName string `json:"app_name"`
	// Used as the `reply to` address in all emails sent to customers, to allow them to receive support.  If you leave this field blank, your RevenueCat account email address will be used.
	SupportEmail NullableString `json:"support_email,omitempty"`
	DefaultCurrency *RCBillingCurrency `json:"default_currency,omitempty"`
}

type _RCBillingAppCreateRcBilling RCBillingAppCreateRcBilling

// NewRCBillingAppCreateRcBilling instantiates a new RCBillingAppCreateRcBilling object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRCBillingAppCreateRcBilling(appName string) *RCBillingAppCreateRcBilling {
	this := RCBillingAppCreateRcBilling{}
	this.AppName = appName
	return &this
}

// NewRCBillingAppCreateRcBillingWithDefaults instantiates a new RCBillingAppCreateRcBilling object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRCBillingAppCreateRcBillingWithDefaults() *RCBillingAppCreateRcBilling {
	this := RCBillingAppCreateRcBilling{}
	return &this
}

// GetStripeAccountId returns the StripeAccountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RCBillingAppCreateRcBilling) GetStripeAccountId() string {
	if o == nil || IsNil(o.StripeAccountId.Get()) {
		var ret string
		return ret
	}
	return *o.StripeAccountId.Get()
}

// GetStripeAccountIdOk returns a tuple with the StripeAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RCBillingAppCreateRcBilling) GetStripeAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StripeAccountId.Get(), o.StripeAccountId.IsSet()
}

// HasStripeAccountId returns a boolean if a field has been set.
func (o *RCBillingAppCreateRcBilling) HasStripeAccountId() bool {
	if o != nil && o.StripeAccountId.IsSet() {
		return true
	}

	return false
}

// SetStripeAccountId gets a reference to the given NullableString and assigns it to the StripeAccountId field.
func (o *RCBillingAppCreateRcBilling) SetStripeAccountId(v string) {
	o.StripeAccountId.Set(&v)
}
// SetStripeAccountIdNil sets the value for StripeAccountId to be an explicit nil
func (o *RCBillingAppCreateRcBilling) SetStripeAccountIdNil() {
	o.StripeAccountId.Set(nil)
}

// UnsetStripeAccountId ensures that no value is present for StripeAccountId, not even an explicit nil
func (o *RCBillingAppCreateRcBilling) UnsetStripeAccountId() {
	o.StripeAccountId.Unset()
}

// GetAppName returns the AppName field value
func (o *RCBillingAppCreateRcBilling) GetAppName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppName
}

// GetAppNameOk returns a tuple with the AppName field value
// and a boolean to check if the value has been set.
func (o *RCBillingAppCreateRcBilling) GetAppNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppName, true
}

// SetAppName sets field value
func (o *RCBillingAppCreateRcBilling) SetAppName(v string) {
	o.AppName = v
}

// GetSupportEmail returns the SupportEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RCBillingAppCreateRcBilling) GetSupportEmail() string {
	if o == nil || IsNil(o.SupportEmail.Get()) {
		var ret string
		return ret
	}
	return *o.SupportEmail.Get()
}

// GetSupportEmailOk returns a tuple with the SupportEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RCBillingAppCreateRcBilling) GetSupportEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupportEmail.Get(), o.SupportEmail.IsSet()
}

// HasSupportEmail returns a boolean if a field has been set.
func (o *RCBillingAppCreateRcBilling) HasSupportEmail() bool {
	if o != nil && o.SupportEmail.IsSet() {
		return true
	}

	return false
}

// SetSupportEmail gets a reference to the given NullableString and assigns it to the SupportEmail field.
func (o *RCBillingAppCreateRcBilling) SetSupportEmail(v string) {
	o.SupportEmail.Set(&v)
}
// SetSupportEmailNil sets the value for SupportEmail to be an explicit nil
func (o *RCBillingAppCreateRcBilling) SetSupportEmailNil() {
	o.SupportEmail.Set(nil)
}

// UnsetSupportEmail ensures that no value is present for SupportEmail, not even an explicit nil
func (o *RCBillingAppCreateRcBilling) UnsetSupportEmail() {
	o.SupportEmail.Unset()
}

// GetDefaultCurrency returns the DefaultCurrency field value if set, zero value otherwise.
func (o *RCBillingAppCreateRcBilling) GetDefaultCurrency() RCBillingCurrency {
	if o == nil || IsNil(o.DefaultCurrency) {
		var ret RCBillingCurrency
		return ret
	}
	return *o.DefaultCurrency
}

// GetDefaultCurrencyOk returns a tuple with the DefaultCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RCBillingAppCreateRcBilling) GetDefaultCurrencyOk() (*RCBillingCurrency, bool) {
	if o == nil || IsNil(o.DefaultCurrency) {
		return nil, false
	}
	return o.DefaultCurrency, true
}

// HasDefaultCurrency returns a boolean if a field has been set.
func (o *RCBillingAppCreateRcBilling) HasDefaultCurrency() bool {
	if o != nil && !IsNil(o.DefaultCurrency) {
		return true
	}

	return false
}

// SetDefaultCurrency gets a reference to the given RCBillingCurrency and assigns it to the DefaultCurrency field.
func (o *RCBillingAppCreateRcBilling) SetDefaultCurrency(v RCBillingCurrency) {
	o.DefaultCurrency = &v
}

func (o RCBillingAppCreateRcBilling) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RCBillingAppCreateRcBilling) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.StripeAccountId.IsSet() {
		toSerialize["stripe_account_id"] = o.StripeAccountId.Get()
	}
	toSerialize["app_name"] = o.AppName
	if o.SupportEmail.IsSet() {
		toSerialize["support_email"] = o.SupportEmail.Get()
	}
	if !IsNil(o.DefaultCurrency) {
		toSerialize["default_currency"] = o.DefaultCurrency
	}
	return toSerialize, nil
}

func (o *RCBillingAppCreateRcBilling) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"app_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRCBillingAppCreateRcBilling := _RCBillingAppCreateRcBilling{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRCBillingAppCreateRcBilling)

	if err != nil {
		return err
	}

	*o = RCBillingAppCreateRcBilling(varRCBillingAppCreateRcBilling)

	return err
}

type NullableRCBillingAppCreateRcBilling struct {
	value *RCBillingAppCreateRcBilling
	isSet bool
}

func (v NullableRCBillingAppCreateRcBilling) Get() *RCBillingAppCreateRcBilling {
	return v.value
}

func (v *NullableRCBillingAppCreateRcBilling) Set(val *RCBillingAppCreateRcBilling) {
	v.value = val
	v.isSet = true
}

func (v NullableRCBillingAppCreateRcBilling) IsSet() bool {
	return v.isSet
}

func (v *NullableRCBillingAppCreateRcBilling) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRCBillingAppCreateRcBilling(val *RCBillingAppCreateRcBilling) *NullableRCBillingAppCreateRcBilling {
	return &NullableRCBillingAppCreateRcBilling{value: val, isSet: true}
}

func (v NullableRCBillingAppCreateRcBilling) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRCBillingAppCreateRcBilling) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


