/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductsList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductsList{}

// ProductsList List of products attached to the entitlement
type ProductsList struct {
	// String representing the object's type. Objects of the same type share the same value. Always has the value `list`.
	Object string `json:"object"`
	// Details about each object.
	Items []Product `json:"items"`
	// URL to access the next page of the Entitlement's products. If not present / null, there is no next page
	NextPage NullableString `json:"next_page"`
	// The URL where this list can be accessed.
	Url string `json:"url"`
}

type _ProductsList ProductsList

// NewProductsList instantiates a new ProductsList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductsList(object string, items []Product, nextPage NullableString, url string) *ProductsList {
	this := ProductsList{}
	this.Object = object
	this.Items = items
	this.NextPage = nextPage
	this.Url = url
	return &this
}

// NewProductsListWithDefaults instantiates a new ProductsList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductsListWithDefaults() *ProductsList {
	this := ProductsList{}
	return &this
}

// GetObject returns the Object field value
func (o *ProductsList) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *ProductsList) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *ProductsList) SetObject(v string) {
	o.Object = v
}

// GetItems returns the Items field value
func (o *ProductsList) GetItems() []Product {
	if o == nil {
		var ret []Product
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ProductsList) GetItemsOk() ([]Product, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ProductsList) SetItems(v []Product) {
	o.Items = v
}

// GetNextPage returns the NextPage field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ProductsList) GetNextPage() string {
	if o == nil || o.NextPage.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextPage.Get()
}

// GetNextPageOk returns a tuple with the NextPage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductsList) GetNextPageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextPage.Get(), o.NextPage.IsSet()
}

// SetNextPage sets field value
func (o *ProductsList) SetNextPage(v string) {
	o.NextPage.Set(&v)
}

// GetUrl returns the Url field value
func (o *ProductsList) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ProductsList) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ProductsList) SetUrl(v string) {
	o.Url = v
}

func (o ProductsList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductsList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["items"] = o.Items
	toSerialize["next_page"] = o.NextPage.Get()
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *ProductsList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"items",
		"next_page",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductsList := _ProductsList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductsList)

	if err != nil {
		return err
	}

	*o = ProductsList(varProductsList)

	return err
}

type NullableProductsList struct {
	value *ProductsList
	isSet bool
}

func (v NullableProductsList) Get() *ProductsList {
	return v.value
}

func (v *NullableProductsList) Set(val *ProductsList) {
	v.value = val
	v.isSet = true
}

func (v NullableProductsList) IsSet() bool {
	return v.isSet
}

func (v *NullableProductsList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductsList(val *ProductsList) *NullableProductsList {
	return &NullableProductsList{value: val, isSet: true}
}

func (v NullableProductsList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductsList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


