/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the UpdateAppRequestStripe type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAppRequestStripe{}

// UpdateAppRequestStripe Stripe type details. Should only be used when type is stripe.
type UpdateAppRequestStripe struct {
	// It needs to be connected to your RevenueCat account. It can be omitted if you only have a single Stripe account connected to your RevenueCat account.
	StripeAccountId *string `json:"stripe_account_id,omitempty"`
}

// NewUpdateAppRequestStripe instantiates a new UpdateAppRequestStripe object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAppRequestStripe() *UpdateAppRequestStripe {
	this := UpdateAppRequestStripe{}
	return &this
}

// NewUpdateAppRequestStripeWithDefaults instantiates a new UpdateAppRequestStripe object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAppRequestStripeWithDefaults() *UpdateAppRequestStripe {
	this := UpdateAppRequestStripe{}
	return &this
}

// GetStripeAccountId returns the StripeAccountId field value if set, zero value otherwise.
func (o *UpdateAppRequestStripe) GetStripeAccountId() string {
	if o == nil || IsNil(o.StripeAccountId) {
		var ret string
		return ret
	}
	return *o.StripeAccountId
}

// GetStripeAccountIdOk returns a tuple with the StripeAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAppRequestStripe) GetStripeAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.StripeAccountId) {
		return nil, false
	}
	return o.StripeAccountId, true
}

// HasStripeAccountId returns a boolean if a field has been set.
func (o *UpdateAppRequestStripe) HasStripeAccountId() bool {
	if o != nil && !IsNil(o.StripeAccountId) {
		return true
	}

	return false
}

// SetStripeAccountId gets a reference to the given string and assigns it to the StripeAccountId field.
func (o *UpdateAppRequestStripe) SetStripeAccountId(v string) {
	o.StripeAccountId = &v
}

func (o UpdateAppRequestStripe) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAppRequestStripe) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StripeAccountId) {
		toSerialize["stripe_account_id"] = o.StripeAccountId
	}
	return toSerialize, nil
}

type NullableUpdateAppRequestStripe struct {
	value *UpdateAppRequestStripe
	isSet bool
}

func (v NullableUpdateAppRequestStripe) Get() *UpdateAppRequestStripe {
	return v.value
}

func (v *NullableUpdateAppRequestStripe) Set(val *UpdateAppRequestStripe) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAppRequestStripe) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAppRequestStripe) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAppRequestStripe(val *UpdateAppRequestStripe) *NullableUpdateAppRequestStripe {
	return &NullableUpdateAppRequestStripe{value: val, isSet: true}
}

func (v NullableUpdateAppRequestStripe) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAppRequestStripe) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


