/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListOfferings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOfferings{}

// ListOfferings struct for ListOfferings
type ListOfferings struct {
	// String representing the object's type. Objects of the same type share the same value. Always has the value `list`.
	Object string `json:"object"`
	// Details about each object.
	Items []Offering `json:"items"`
	// URL to access the next page of the project's offerings. If not present / null, there is no next page
	NextPage NullableString `json:"next_page"`
	// The URL where this list can be accessed.
	Url string `json:"url"`
}

type _ListOfferings ListOfferings

// NewListOfferings instantiates a new ListOfferings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOfferings(object string, items []Offering, nextPage NullableString, url string) *ListOfferings {
	this := ListOfferings{}
	this.Object = object
	this.Items = items
	this.NextPage = nextPage
	this.Url = url
	return &this
}

// NewListOfferingsWithDefaults instantiates a new ListOfferings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOfferingsWithDefaults() *ListOfferings {
	this := ListOfferings{}
	return &this
}

// GetObject returns the Object field value
func (o *ListOfferings) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *ListOfferings) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *ListOfferings) SetObject(v string) {
	o.Object = v
}

// GetItems returns the Items field value
func (o *ListOfferings) GetItems() []Offering {
	if o == nil {
		var ret []Offering
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListOfferings) GetItemsOk() ([]Offering, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListOfferings) SetItems(v []Offering) {
	o.Items = v
}

// GetNextPage returns the NextPage field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListOfferings) GetNextPage() string {
	if o == nil || o.NextPage.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextPage.Get()
}

// GetNextPageOk returns a tuple with the NextPage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListOfferings) GetNextPageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextPage.Get(), o.NextPage.IsSet()
}

// SetNextPage sets field value
func (o *ListOfferings) SetNextPage(v string) {
	o.NextPage.Set(&v)
}

// GetUrl returns the Url field value
func (o *ListOfferings) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ListOfferings) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ListOfferings) SetUrl(v string) {
	o.Url = v
}

func (o ListOfferings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOfferings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["items"] = o.Items
	toSerialize["next_page"] = o.NextPage.Get()
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *ListOfferings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"items",
		"next_page",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListOfferings := _ListOfferings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListOfferings)

	if err != nil {
		return err
	}

	*o = ListOfferings(varListOfferings)

	return err
}

type NullableListOfferings struct {
	value *ListOfferings
	isSet bool
}

func (v NullableListOfferings) Get() *ListOfferings {
	return v.value
}

func (v *NullableListOfferings) Set(val *ListOfferings) {
	v.value = val
	v.isSet = true
}

func (v NullableListOfferings) IsSet() bool {
	return v.isSet
}

func (v *NullableListOfferings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOfferings(val *ListOfferings) *NullableListOfferings {
	return &NullableListOfferings{value: val, isSet: true}
}

func (v NullableListOfferings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOfferings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


