/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCustomerRequestAttributesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCustomerRequestAttributesInner{}

// CreateCustomerRequestAttributesInner struct for CreateCustomerRequestAttributesInner
type CreateCustomerRequestAttributesInner struct {
	Name CreateCustomerRequestAttributesInnerName `json:"name"`
	// The value of the attribute
	Value string `json:"value"`
}

type _CreateCustomerRequestAttributesInner CreateCustomerRequestAttributesInner

// NewCreateCustomerRequestAttributesInner instantiates a new CreateCustomerRequestAttributesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCustomerRequestAttributesInner(name CreateCustomerRequestAttributesInnerName, value string) *CreateCustomerRequestAttributesInner {
	this := CreateCustomerRequestAttributesInner{}
	this.Name = name
	this.Value = value
	return &this
}

// NewCreateCustomerRequestAttributesInnerWithDefaults instantiates a new CreateCustomerRequestAttributesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCustomerRequestAttributesInnerWithDefaults() *CreateCustomerRequestAttributesInner {
	this := CreateCustomerRequestAttributesInner{}
	return &this
}

// GetName returns the Name field value
func (o *CreateCustomerRequestAttributesInner) GetName() CreateCustomerRequestAttributesInnerName {
	if o == nil {
		var ret CreateCustomerRequestAttributesInnerName
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateCustomerRequestAttributesInner) GetNameOk() (*CreateCustomerRequestAttributesInnerName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateCustomerRequestAttributesInner) SetName(v CreateCustomerRequestAttributesInnerName) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *CreateCustomerRequestAttributesInner) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CreateCustomerRequestAttributesInner) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CreateCustomerRequestAttributesInner) SetValue(v string) {
	o.Value = v
}

func (o CreateCustomerRequestAttributesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCustomerRequestAttributesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *CreateCustomerRequestAttributesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCustomerRequestAttributesInner := _CreateCustomerRequestAttributesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCustomerRequestAttributesInner)

	if err != nil {
		return err
	}

	*o = CreateCustomerRequestAttributesInner(varCreateCustomerRequestAttributesInner)

	return err
}

type NullableCreateCustomerRequestAttributesInner struct {
	value *CreateCustomerRequestAttributesInner
	isSet bool
}

func (v NullableCreateCustomerRequestAttributesInner) Get() *CreateCustomerRequestAttributesInner {
	return v.value
}

func (v *NullableCreateCustomerRequestAttributesInner) Set(val *CreateCustomerRequestAttributesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCustomerRequestAttributesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCustomerRequestAttributesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCustomerRequestAttributesInner(val *CreateCustomerRequestAttributesInner) *NullableCreateCustomerRequestAttributesInner {
	return &NullableCreateCustomerRequestAttributesInner{value: val, isSet: true}
}

func (v NullableCreateCustomerRequestAttributesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCustomerRequestAttributesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


