/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateProductInStore201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProductInStore201Response{}

// CreateProductInStore201Response struct for CreateProductInStore201Response
type CreateProductInStore201Response struct {
	CreatedProduct StoreProduct `json:"created_product"`
}

type _CreateProductInStore201Response CreateProductInStore201Response

// NewCreateProductInStore201Response instantiates a new CreateProductInStore201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProductInStore201Response(createdProduct StoreProduct) *CreateProductInStore201Response {
	this := CreateProductInStore201Response{}
	this.CreatedProduct = createdProduct
	return &this
}

// NewCreateProductInStore201ResponseWithDefaults instantiates a new CreateProductInStore201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProductInStore201ResponseWithDefaults() *CreateProductInStore201Response {
	this := CreateProductInStore201Response{}
	return &this
}

// GetCreatedProduct returns the CreatedProduct field value
func (o *CreateProductInStore201Response) GetCreatedProduct() StoreProduct {
	if o == nil {
		var ret StoreProduct
		return ret
	}

	return o.CreatedProduct
}

// GetCreatedProductOk returns a tuple with the CreatedProduct field value
// and a boolean to check if the value has been set.
func (o *CreateProductInStore201Response) GetCreatedProductOk() (*StoreProduct, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedProduct, true
}

// SetCreatedProduct sets field value
func (o *CreateProductInStore201Response) SetCreatedProduct(v StoreProduct) {
	o.CreatedProduct = v
}

func (o CreateProductInStore201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProductInStore201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_product"] = o.CreatedProduct
	return toSerialize, nil
}

func (o *CreateProductInStore201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_product",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProductInStore201Response := _CreateProductInStore201Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateProductInStore201Response)

	if err != nil {
		return err
	}

	*o = CreateProductInStore201Response(varCreateProductInStore201Response)

	return err
}

type NullableCreateProductInStore201Response struct {
	value *CreateProductInStore201Response
	isSet bool
}

func (v NullableCreateProductInStore201Response) Get() *CreateProductInStore201Response {
	return v.value
}

func (v *NullableCreateProductInStore201Response) Set(val *CreateProductInStore201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProductInStore201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProductInStore201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProductInStore201Response(val *CreateProductInStore201Response) *NullableCreateProductInStore201Response {
	return &NullableCreateProductInStore201Response{value: val, isSet: true}
}

func (v NullableCreateProductInStore201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProductInStore201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


