/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the PaddleAppCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaddleAppCreate{}

// PaddleAppCreate struct for PaddleAppCreate
type PaddleAppCreate struct {
	Paddle NullablePaddleAppCreatePaddle `json:"paddle,omitempty"`
}

// NewPaddleAppCreate instantiates a new PaddleAppCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaddleAppCreate() *PaddleAppCreate {
	this := PaddleAppCreate{}
	return &this
}

// NewPaddleAppCreateWithDefaults instantiates a new PaddleAppCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaddleAppCreateWithDefaults() *PaddleAppCreate {
	this := PaddleAppCreate{}
	return &this
}

// GetPaddle returns the Paddle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaddleAppCreate) GetPaddle() PaddleAppCreatePaddle {
	if o == nil || IsNil(o.Paddle.Get()) {
		var ret PaddleAppCreatePaddle
		return ret
	}
	return *o.Paddle.Get()
}

// GetPaddleOk returns a tuple with the Paddle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaddleAppCreate) GetPaddleOk() (*PaddleAppCreatePaddle, bool) {
	if o == nil {
		return nil, false
	}
	return o.Paddle.Get(), o.Paddle.IsSet()
}

// HasPaddle returns a boolean if a field has been set.
func (o *PaddleAppCreate) HasPaddle() bool {
	if o != nil && o.Paddle.IsSet() {
		return true
	}

	return false
}

// SetPaddle gets a reference to the given NullablePaddleAppCreatePaddle and assigns it to the Paddle field.
func (o *PaddleAppCreate) SetPaddle(v PaddleAppCreatePaddle) {
	o.Paddle.Set(&v)
}
// SetPaddleNil sets the value for Paddle to be an explicit nil
func (o *PaddleAppCreate) SetPaddleNil() {
	o.Paddle.Set(nil)
}

// UnsetPaddle ensures that no value is present for Paddle, not even an explicit nil
func (o *PaddleAppCreate) UnsetPaddle() {
	o.Paddle.Unset()
}

func (o PaddleAppCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaddleAppCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Paddle.IsSet() {
		toSerialize["paddle"] = o.Paddle.Get()
	}
	return toSerialize, nil
}

type NullablePaddleAppCreate struct {
	value *PaddleAppCreate
	isSet bool
}

func (v NullablePaddleAppCreate) Get() *PaddleAppCreate {
	return v.value
}

func (v *NullablePaddleAppCreate) Set(val *PaddleAppCreate) {
	v.value = val
	v.isSet = true
}

func (v NullablePaddleAppCreate) IsSet() bool {
	return v.isSet
}

func (v *NullablePaddleAppCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaddleAppCreate(val *PaddleAppCreate) *NullablePaddleAppCreate {
	return &NullablePaddleAppCreate{value: val, isSet: true}
}

func (v NullablePaddleAppCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaddleAppCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


