/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppStoreAppAppStore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppStoreAppAppStore{}

// AppStoreAppAppStore App Store type details
type AppStoreAppAppStore struct {
	// The bundle ID of the app
	BundleId string `json:"bundle_id"`
}

type _AppStoreAppAppStore AppStoreAppAppStore

// NewAppStoreAppAppStore instantiates a new AppStoreAppAppStore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppStoreAppAppStore(bundleId string) *AppStoreAppAppStore {
	this := AppStoreAppAppStore{}
	this.BundleId = bundleId
	return &this
}

// NewAppStoreAppAppStoreWithDefaults instantiates a new AppStoreAppAppStore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppStoreAppAppStoreWithDefaults() *AppStoreAppAppStore {
	this := AppStoreAppAppStore{}
	return &this
}

// GetBundleId returns the BundleId field value
func (o *AppStoreAppAppStore) GetBundleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BundleId
}

// GetBundleIdOk returns a tuple with the BundleId field value
// and a boolean to check if the value has been set.
func (o *AppStoreAppAppStore) GetBundleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BundleId, true
}

// SetBundleId sets field value
func (o *AppStoreAppAppStore) SetBundleId(v string) {
	o.BundleId = v
}

func (o AppStoreAppAppStore) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppStoreAppAppStore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bundle_id"] = o.BundleId
	return toSerialize, nil
}

func (o *AppStoreAppAppStore) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bundle_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppStoreAppAppStore := _AppStoreAppAppStore{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppStoreAppAppStore)

	if err != nil {
		return err
	}

	*o = AppStoreAppAppStore(varAppStoreAppAppStore)

	return err
}

type NullableAppStoreAppAppStore struct {
	value *AppStoreAppAppStore
	isSet bool
}

func (v NullableAppStoreAppAppStore) Get() *AppStoreAppAppStore {
	return v.value
}

func (v *NullableAppStoreAppAppStore) Set(val *AppStoreAppAppStore) {
	v.value = val
	v.isSet = true
}

func (v NullableAppStoreAppAppStore) IsSet() bool {
	return v.isSet
}

func (v *NullableAppStoreAppAppStore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppStoreAppAppStore(val *AppStoreAppAppStore) *NullableAppStoreAppAppStore {
	return &NullableAppStoreAppAppStore{value: val, isSet: true}
}

func (v NullableAppStoreAppAppStore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppStoreAppAppStore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


