/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the StripeAppStripe type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StripeAppStripe{}

// StripeAppStripe Stripe type details
type StripeAppStripe struct {
	// Stripe account connected to your RevenueCat account.
	StripeAccountId NullableString `json:"stripe_account_id,omitempty"`
}

// NewStripeAppStripe instantiates a new StripeAppStripe object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStripeAppStripe() *StripeAppStripe {
	this := StripeAppStripe{}
	return &this
}

// NewStripeAppStripeWithDefaults instantiates a new StripeAppStripe object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStripeAppStripeWithDefaults() *StripeAppStripe {
	this := StripeAppStripe{}
	return &this
}

// GetStripeAccountId returns the StripeAccountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StripeAppStripe) GetStripeAccountId() string {
	if o == nil || IsNil(o.StripeAccountId.Get()) {
		var ret string
		return ret
	}
	return *o.StripeAccountId.Get()
}

// GetStripeAccountIdOk returns a tuple with the StripeAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StripeAppStripe) GetStripeAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StripeAccountId.Get(), o.StripeAccountId.IsSet()
}

// HasStripeAccountId returns a boolean if a field has been set.
func (o *StripeAppStripe) HasStripeAccountId() bool {
	if o != nil && o.StripeAccountId.IsSet() {
		return true
	}

	return false
}

// SetStripeAccountId gets a reference to the given NullableString and assigns it to the StripeAccountId field.
func (o *StripeAppStripe) SetStripeAccountId(v string) {
	o.StripeAccountId.Set(&v)
}
// SetStripeAccountIdNil sets the value for StripeAccountId to be an explicit nil
func (o *StripeAppStripe) SetStripeAccountIdNil() {
	o.StripeAccountId.Set(nil)
}

// UnsetStripeAccountId ensures that no value is present for StripeAccountId, not even an explicit nil
func (o *StripeAppStripe) UnsetStripeAccountId() {
	o.StripeAccountId.Unset()
}

func (o StripeAppStripe) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StripeAppStripe) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.StripeAccountId.IsSet() {
		toSerialize["stripe_account_id"] = o.StripeAccountId.Get()
	}
	return toSerialize, nil
}

type NullableStripeAppStripe struct {
	value *StripeAppStripe
	isSet bool
}

func (v NullableStripeAppStripe) Get() *StripeAppStripe {
	return v.value
}

func (v *NullableStripeAppStripe) Set(val *StripeAppStripe) {
	v.value = val
	v.isSet = true
}

func (v NullableStripeAppStripe) IsSet() bool {
	return v.isSet
}

func (v *NullableStripeAppStripe) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStripeAppStripe(val *StripeAppStripe) *NullableStripeAppStripe {
	return &NullableStripeAppStripe{value: val, isSet: true}
}

func (v NullableStripeAppStripe) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStripeAppStripe) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


