/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CreateProductInStoreRequestStoreInformation - Store-specific information for creating the product in the store
type CreateProductInStoreRequestStoreInformation struct {
	CreateAppStoreConnectSubscriptionInput *CreateAppStoreConnectSubscriptionInput
	MapmapOfStringAny *map[string]interface{}
}

// CreateAppStoreConnectSubscriptionInputAsCreateProductInStoreRequestStoreInformation is a convenience function that returns CreateAppStoreConnectSubscriptionInput wrapped in CreateProductInStoreRequestStoreInformation
func CreateAppStoreConnectSubscriptionInputAsCreateProductInStoreRequestStoreInformation(v *CreateAppStoreConnectSubscriptionInput) CreateProductInStoreRequestStoreInformation {
	return CreateProductInStoreRequestStoreInformation{
		CreateAppStoreConnectSubscriptionInput: v,
	}
}

// map[string]interface{}AsCreateProductInStoreRequestStoreInformation is a convenience function that returns map[string]interface{} wrapped in CreateProductInStoreRequestStoreInformation
func MapmapOfStringAnyAsCreateProductInStoreRequestStoreInformation(v *map[string]interface{}) CreateProductInStoreRequestStoreInformation {
	return CreateProductInStoreRequestStoreInformation{
		MapmapOfStringAny: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateProductInStoreRequestStoreInformation) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CreateAppStoreConnectSubscriptionInput
	err = newStrictDecoder(data).Decode(&dst.CreateAppStoreConnectSubscriptionInput)
	if err == nil {
		jsonCreateAppStoreConnectSubscriptionInput, _ := json.Marshal(dst.CreateAppStoreConnectSubscriptionInput)
		if string(jsonCreateAppStoreConnectSubscriptionInput) == "{}" { // empty struct
			dst.CreateAppStoreConnectSubscriptionInput = nil
		} else {
			if err = validator.Validate(dst.CreateAppStoreConnectSubscriptionInput); err != nil {
				dst.CreateAppStoreConnectSubscriptionInput = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateAppStoreConnectSubscriptionInput = nil
	}

	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateAppStoreConnectSubscriptionInput = nil
		dst.MapmapOfStringAny = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CreateProductInStoreRequestStoreInformation)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CreateProductInStoreRequestStoreInformation)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateProductInStoreRequestStoreInformation) MarshalJSON() ([]byte, error) {
	if src.CreateAppStoreConnectSubscriptionInput != nil {
		return json.Marshal(&src.CreateAppStoreConnectSubscriptionInput)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateProductInStoreRequestStoreInformation) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CreateAppStoreConnectSubscriptionInput != nil {
		return obj.CreateAppStoreConnectSubscriptionInput
	}

	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CreateProductInStoreRequestStoreInformation) GetActualInstanceValue() (interface{}) {
	if obj.CreateAppStoreConnectSubscriptionInput != nil {
		return *obj.CreateAppStoreConnectSubscriptionInput
	}

	if obj.MapmapOfStringAny != nil {
		return *obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

type NullableCreateProductInStoreRequestStoreInformation struct {
	value *CreateProductInStoreRequestStoreInformation
	isSet bool
}

func (v NullableCreateProductInStoreRequestStoreInformation) Get() *CreateProductInStoreRequestStoreInformation {
	return v.value
}

func (v *NullableCreateProductInStoreRequestStoreInformation) Set(val *CreateProductInStoreRequestStoreInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProductInStoreRequestStoreInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProductInStoreRequestStoreInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProductInStoreRequestStoreInformation(val *CreateProductInStoreRequestStoreInformation) *NullableCreateProductInStoreRequestStoreInformation {
	return &NullableCreateProductInStoreRequestStoreInformation{value: val, isSet: true}
}

func (v NullableCreateProductInStoreRequestStoreInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProductInStoreRequestStoreInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


