/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"fmt"
)

// CustomerAttributeReservedName the model 'CustomerAttributeReservedName'
type CustomerAttributeReservedName string

// List of CustomerAttributeReservedName
const (
	_AD CustomerAttributeReservedName = "$ad"
	_AD_GROUP CustomerAttributeReservedName = "$adGroup"
	_ADJUST_ID CustomerAttributeReservedName = "$adjustId"
	_AIRSHIP_CHANNEL_ID CustomerAttributeReservedName = "$airshipChannelId"
	_AMAZON_AD_ID CustomerAttributeReservedName = "$amazonAdId"
	_AMPLITUDE_DEVICE_ID CustomerAttributeReservedName = "$amplitudeDeviceId"
	_AMPLITUDE_USER_ID CustomerAttributeReservedName = "$amplitudeUserId"
	_APPLE_REFUND_HANDLING_PREFERENCE CustomerAttributeReservedName = "$appleRefundHandlingPreference"
	_APNS_TOKENS CustomerAttributeReservedName = "$apnsTokens"
	_APPSFLYER_ID CustomerAttributeReservedName = "$appsflyerId"
	_APPSFLYER_SHARING_FILTER CustomerAttributeReservedName = "$appsflyerSharingFilter"
	_ATT_CONSENT_STATUS CustomerAttributeReservedName = "$attConsentStatus"
	_BRANCH_ID CustomerAttributeReservedName = "$branchId"
	_BRAZE_ALIAS_LABEL CustomerAttributeReservedName = "$brazeAliasLabel"
	_BRAZE_ALIAS_NAME CustomerAttributeReservedName = "$brazeAliasName"
	_CAMPAIGN CustomerAttributeReservedName = "$campaign"
	_CLEVERTAP_ID CustomerAttributeReservedName = "$clevertapId"
	_CREATIVE CustomerAttributeReservedName = "$creative"
	_CUSTOMERIO_ID CustomerAttributeReservedName = "$customerioId"
	_DISPLAY_NAME CustomerAttributeReservedName = "$displayName"
	_EMAIL CustomerAttributeReservedName = "$email"
	_FB_ANON_ID CustomerAttributeReservedName = "$fbAnonId"
	_FCM_TOKENS CustomerAttributeReservedName = "$fcmTokens"
	_FIREBASE_APP_INSTANCE_ID CustomerAttributeReservedName = "$firebaseAppInstanceId"
	_GPS_AD_ID CustomerAttributeReservedName = "$gpsAdId"
	_IDFA CustomerAttributeReservedName = "$idfa"
	_IDFV CustomerAttributeReservedName = "$idfv"
	_IP CustomerAttributeReservedName = "$ip"
	_ITERABLE_CAMPAIGN_ID CustomerAttributeReservedName = "$iterableCampaignId"
	_ITERABLE_TEMPLATE_ID CustomerAttributeReservedName = "$iterableTemplateId"
	_ITERABLE_USER_ID CustomerAttributeReservedName = "$iterableUserId"
	_KEYWORD CustomerAttributeReservedName = "$keyword"
	_KOCHAVA_DEVICE_ID CustomerAttributeReservedName = "$kochavaDeviceId"
	_MEDIA_SOURCE CustomerAttributeReservedName = "$mediaSource"
	_MIXPANEL_DISTINCT_ID CustomerAttributeReservedName = "$mixpanelDistinctId"
	_MPARTICLE_ID CustomerAttributeReservedName = "$mparticleId"
	_ONESIGNAL_ID CustomerAttributeReservedName = "$onesignalId"
	_ONESIGNAL_USER_ID CustomerAttributeReservedName = "$onesignalUserId"
	_PHONE_NUMBER CustomerAttributeReservedName = "$phoneNumber"
	_POSTHOG_USER_ID CustomerAttributeReservedName = "$posthogUserId"
	_TELEMETRY_DECK_USER_ID CustomerAttributeReservedName = "$telemetryDeckUserId"
	_TELEMETRY_DECK_APP_ID CustomerAttributeReservedName = "$telemetryDeckAppId"
	TELEMETRY_DECK_USER_ID CustomerAttributeReservedName = "telemetry_deck_user_id"
	TELEMETRY_DECK_APP_ID CustomerAttributeReservedName = "telemetry_deck_app_id"
	_SEGMENT_ID CustomerAttributeReservedName = "$segmentId"
	_TENJIN_ID CustomerAttributeReservedName = "$tenjinId"
	_DEVICE_VERSION CustomerAttributeReservedName = "$deviceVersion"
)

// All allowed values of CustomerAttributeReservedName enum
var AllowedCustomerAttributeReservedNameEnumValues = []CustomerAttributeReservedName{
	"$ad",
	"$adGroup",
	"$adjustId",
	"$airshipChannelId",
	"$amazonAdId",
	"$amplitudeDeviceId",
	"$amplitudeUserId",
	"$appleRefundHandlingPreference",
	"$apnsTokens",
	"$appsflyerId",
	"$appsflyerSharingFilter",
	"$attConsentStatus",
	"$branchId",
	"$brazeAliasLabel",
	"$brazeAliasName",
	"$campaign",
	"$clevertapId",
	"$creative",
	"$customerioId",
	"$displayName",
	"$email",
	"$fbAnonId",
	"$fcmTokens",
	"$firebaseAppInstanceId",
	"$gpsAdId",
	"$idfa",
	"$idfv",
	"$ip",
	"$iterableCampaignId",
	"$iterableTemplateId",
	"$iterableUserId",
	"$keyword",
	"$kochavaDeviceId",
	"$mediaSource",
	"$mixpanelDistinctId",
	"$mparticleId",
	"$onesignalId",
	"$onesignalUserId",
	"$phoneNumber",
	"$posthogUserId",
	"$telemetryDeckUserId",
	"$telemetryDeckAppId",
	"telemetry_deck_user_id",
	"telemetry_deck_app_id",
	"$segmentId",
	"$tenjinId",
	"$deviceVersion",
}

func (v *CustomerAttributeReservedName) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CustomerAttributeReservedName(value)
	for _, existing := range AllowedCustomerAttributeReservedNameEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CustomerAttributeReservedName", value)
}

// NewCustomerAttributeReservedNameFromValue returns a pointer to a valid CustomerAttributeReservedName
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCustomerAttributeReservedNameFromValue(v string) (*CustomerAttributeReservedName, error) {
	ev := CustomerAttributeReservedName(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CustomerAttributeReservedName: valid values are %v", v, AllowedCustomerAttributeReservedNameEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CustomerAttributeReservedName) IsValid() bool {
	for _, existing := range AllowedCustomerAttributeReservedNameEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CustomerAttributeReservedName value
func (v CustomerAttributeReservedName) Ptr() *CustomerAttributeReservedName {
	return &v
}

type NullableCustomerAttributeReservedName struct {
	value *CustomerAttributeReservedName
	isSet bool
}

func (v NullableCustomerAttributeReservedName) Get() *CustomerAttributeReservedName {
	return v.value
}

func (v *NullableCustomerAttributeReservedName) Set(val *CustomerAttributeReservedName) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerAttributeReservedName) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerAttributeReservedName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerAttributeReservedName(val *CustomerAttributeReservedName) *NullableCustomerAttributeReservedName {
	return &NullableCustomerAttributeReservedName{value: val, isSet: true}
}

func (v NullableCustomerAttributeReservedName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerAttributeReservedName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

