/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AttachProductsToEntitlementRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttachProductsToEntitlementRequest{}

// AttachProductsToEntitlementRequest struct for AttachProductsToEntitlementRequest
type AttachProductsToEntitlementRequest struct {
	// IDs of the products to be attached to the entitlement.
	ProductIds []string `json:"product_ids"`
}

type _AttachProductsToEntitlementRequest AttachProductsToEntitlementRequest

// NewAttachProductsToEntitlementRequest instantiates a new AttachProductsToEntitlementRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachProductsToEntitlementRequest(productIds []string) *AttachProductsToEntitlementRequest {
	this := AttachProductsToEntitlementRequest{}
	this.ProductIds = productIds
	return &this
}

// NewAttachProductsToEntitlementRequestWithDefaults instantiates a new AttachProductsToEntitlementRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachProductsToEntitlementRequestWithDefaults() *AttachProductsToEntitlementRequest {
	this := AttachProductsToEntitlementRequest{}
	return &this
}

// GetProductIds returns the ProductIds field value
func (o *AttachProductsToEntitlementRequest) GetProductIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ProductIds
}

// GetProductIdsOk returns a tuple with the ProductIds field value
// and a boolean to check if the value has been set.
func (o *AttachProductsToEntitlementRequest) GetProductIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductIds, true
}

// SetProductIds sets field value
func (o *AttachProductsToEntitlementRequest) SetProductIds(v []string) {
	o.ProductIds = v
}

func (o AttachProductsToEntitlementRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttachProductsToEntitlementRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["product_ids"] = o.ProductIds
	return toSerialize, nil
}

func (o *AttachProductsToEntitlementRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"product_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAttachProductsToEntitlementRequest := _AttachProductsToEntitlementRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAttachProductsToEntitlementRequest)

	if err != nil {
		return err
	}

	*o = AttachProductsToEntitlementRequest(varAttachProductsToEntitlementRequest)

	return err
}

type NullableAttachProductsToEntitlementRequest struct {
	value *AttachProductsToEntitlementRequest
	isSet bool
}

func (v NullableAttachProductsToEntitlementRequest) Get() *AttachProductsToEntitlementRequest {
	return v.value
}

func (v *NullableAttachProductsToEntitlementRequest) Set(val *AttachProductsToEntitlementRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachProductsToEntitlementRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachProductsToEntitlementRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachProductsToEntitlementRequest(val *AttachProductsToEntitlementRequest) *NullableAttachProductsToEntitlementRequest {
	return &NullableAttachProductsToEntitlementRequest{value: val, isSet: true}
}

func (v NullableAttachProductsToEntitlementRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachProductsToEntitlementRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


