/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EntitlementList1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntitlementList1{}

// EntitlementList1 struct for EntitlementList1
type EntitlementList1 struct {
	// String representing the object's type. Objects of the same type share the same value. Always has the value `list`.
	Object string `json:"object"`
	// Details about each object.
	Items []Entitlement `json:"items"`
	// URL to access the next page of the customer's entitlements. If not present / null, there is no next page
	NextPage NullableString `json:"next_page"`
	// The URL where this list can be accessed.
	Url string `json:"url"`
}

type _EntitlementList1 EntitlementList1

// NewEntitlementList1 instantiates a new EntitlementList1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntitlementList1(object string, items []Entitlement, nextPage NullableString, url string) *EntitlementList1 {
	this := EntitlementList1{}
	this.Object = object
	this.Items = items
	this.NextPage = nextPage
	this.Url = url
	return &this
}

// NewEntitlementList1WithDefaults instantiates a new EntitlementList1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntitlementList1WithDefaults() *EntitlementList1 {
	this := EntitlementList1{}
	return &this
}

// GetObject returns the Object field value
func (o *EntitlementList1) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *EntitlementList1) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *EntitlementList1) SetObject(v string) {
	o.Object = v
}

// GetItems returns the Items field value
func (o *EntitlementList1) GetItems() []Entitlement {
	if o == nil {
		var ret []Entitlement
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *EntitlementList1) GetItemsOk() ([]Entitlement, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *EntitlementList1) SetItems(v []Entitlement) {
	o.Items = v
}

// GetNextPage returns the NextPage field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EntitlementList1) GetNextPage() string {
	if o == nil || o.NextPage.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextPage.Get()
}

// GetNextPageOk returns a tuple with the NextPage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntitlementList1) GetNextPageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextPage.Get(), o.NextPage.IsSet()
}

// SetNextPage sets field value
func (o *EntitlementList1) SetNextPage(v string) {
	o.NextPage.Set(&v)
}

// GetUrl returns the Url field value
func (o *EntitlementList1) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *EntitlementList1) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *EntitlementList1) SetUrl(v string) {
	o.Url = v
}

func (o EntitlementList1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntitlementList1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["items"] = o.Items
	toSerialize["next_page"] = o.NextPage.Get()
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *EntitlementList1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"items",
		"next_page",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntitlementList1 := _EntitlementList1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntitlementList1)

	if err != nil {
		return err
	}

	*o = EntitlementList1(varEntitlementList1)

	return err
}

type NullableEntitlementList1 struct {
	value *EntitlementList1
	isSet bool
}

func (v NullableEntitlementList1) Get() *EntitlementList1 {
	return v.value
}

func (v *NullableEntitlementList1) Set(val *EntitlementList1) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitlementList1) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitlementList1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitlementList1(val *EntitlementList1) *NullableEntitlementList1 {
	return &NullableEntitlementList1{value: val, isSet: true}
}

func (v NullableEntitlementList1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitlementList1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


