/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PackageProductIDAssociation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PackageProductIDAssociation{}

// PackageProductIDAssociation struct for PackageProductIDAssociation
type PackageProductIDAssociation struct {
	ProductId string `json:"product_id"`
	EligibilityCriteria EligibilityCriteria `json:"eligibility_criteria"`
}

type _PackageProductIDAssociation PackageProductIDAssociation

// NewPackageProductIDAssociation instantiates a new PackageProductIDAssociation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPackageProductIDAssociation(productId string, eligibilityCriteria EligibilityCriteria) *PackageProductIDAssociation {
	this := PackageProductIDAssociation{}
	this.ProductId = productId
	this.EligibilityCriteria = eligibilityCriteria
	return &this
}

// NewPackageProductIDAssociationWithDefaults instantiates a new PackageProductIDAssociation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPackageProductIDAssociationWithDefaults() *PackageProductIDAssociation {
	this := PackageProductIDAssociation{}
	return &this
}

// GetProductId returns the ProductId field value
func (o *PackageProductIDAssociation) GetProductId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value
// and a boolean to check if the value has been set.
func (o *PackageProductIDAssociation) GetProductIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductId, true
}

// SetProductId sets field value
func (o *PackageProductIDAssociation) SetProductId(v string) {
	o.ProductId = v
}

// GetEligibilityCriteria returns the EligibilityCriteria field value
func (o *PackageProductIDAssociation) GetEligibilityCriteria() EligibilityCriteria {
	if o == nil {
		var ret EligibilityCriteria
		return ret
	}

	return o.EligibilityCriteria
}

// GetEligibilityCriteriaOk returns a tuple with the EligibilityCriteria field value
// and a boolean to check if the value has been set.
func (o *PackageProductIDAssociation) GetEligibilityCriteriaOk() (*EligibilityCriteria, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EligibilityCriteria, true
}

// SetEligibilityCriteria sets field value
func (o *PackageProductIDAssociation) SetEligibilityCriteria(v EligibilityCriteria) {
	o.EligibilityCriteria = v
}

func (o PackageProductIDAssociation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PackageProductIDAssociation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["product_id"] = o.ProductId
	toSerialize["eligibility_criteria"] = o.EligibilityCriteria
	return toSerialize, nil
}

func (o *PackageProductIDAssociation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"product_id",
		"eligibility_criteria",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPackageProductIDAssociation := _PackageProductIDAssociation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPackageProductIDAssociation)

	if err != nil {
		return err
	}

	*o = PackageProductIDAssociation(varPackageProductIDAssociation)

	return err
}

type NullablePackageProductIDAssociation struct {
	value *PackageProductIDAssociation
	isSet bool
}

func (v NullablePackageProductIDAssociation) Get() *PackageProductIDAssociation {
	return v.value
}

func (v *NullablePackageProductIDAssociation) Set(val *PackageProductIDAssociation) {
	v.value = val
	v.isSet = true
}

func (v NullablePackageProductIDAssociation) IsSet() bool {
	return v.isSet
}

func (v *NullablePackageProductIDAssociation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePackageProductIDAssociation(val *PackageProductIDAssociation) *NullablePackageProductIDAssociation {
	return &NullablePackageProductIDAssociation{value: val, isSet: true}
}

func (v NullablePackageProductIDAssociation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePackageProductIDAssociation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


