/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeletedObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletedObject{}

// DeletedObject struct for DeletedObject
type DeletedObject struct {
	// The type of the deleted object
	Object string `json:"object"`
	// The ID of the deleted object
	Id string `json:"id"`
	// The date when the object was deleted in ms since epoch
	DeletedAt int64 `json:"deleted_at"`
}

type _DeletedObject DeletedObject

// NewDeletedObject instantiates a new DeletedObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletedObject(object string, id string, deletedAt int64) *DeletedObject {
	this := DeletedObject{}
	this.Object = object
	this.Id = id
	this.DeletedAt = deletedAt
	return &this
}

// NewDeletedObjectWithDefaults instantiates a new DeletedObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletedObjectWithDefaults() *DeletedObject {
	this := DeletedObject{}
	return &this
}

// GetObject returns the Object field value
func (o *DeletedObject) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *DeletedObject) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *DeletedObject) SetObject(v string) {
	o.Object = v
}

// GetId returns the Id field value
func (o *DeletedObject) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeletedObject) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeletedObject) SetId(v string) {
	o.Id = v
}

// GetDeletedAt returns the DeletedAt field value
func (o *DeletedObject) GetDeletedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value
// and a boolean to check if the value has been set.
func (o *DeletedObject) GetDeletedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeletedAt, true
}

// SetDeletedAt sets field value
func (o *DeletedObject) SetDeletedAt(v int64) {
	o.DeletedAt = v
}

func (o DeletedObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletedObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["id"] = o.Id
	toSerialize["deleted_at"] = o.DeletedAt
	return toSerialize, nil
}

func (o *DeletedObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"id",
		"deleted_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeletedObject := _DeletedObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeletedObject)

	if err != nil {
		return err
	}

	*o = DeletedObject(varDeletedObject)

	return err
}

type NullableDeletedObject struct {
	value *DeletedObject
	isSet bool
}

func (v NullableDeletedObject) Get() *DeletedObject {
	return v.value
}

func (v *NullableDeletedObject) Set(val *DeletedObject) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletedObject) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletedObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletedObject(val *DeletedObject) *NullableDeletedObject {
	return &NullableDeletedObject{value: val, isSet: true}
}

func (v NullableDeletedObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletedObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


