/*
Developer API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revenuecat

import (
	"encoding/json"
	"fmt"
)

// PurchaseRevenueInUsd - The revenue generated by the purchase in USD
type PurchaseRevenueInUsd struct {
	MonetaryAmount *MonetaryAmount
}

// MonetaryAmountAsPurchaseRevenueInUsd is a convenience function that returns MonetaryAmount wrapped in PurchaseRevenueInUsd
func MonetaryAmountAsPurchaseRevenueInUsd(v *MonetaryAmount) PurchaseRevenueInUsd {
	return PurchaseRevenueInUsd{
		MonetaryAmount: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PurchaseRevenueInUsd) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into MonetaryAmount
	err = newStrictDecoder(data).Decode(&dst.MonetaryAmount)
	if err == nil {
		jsonMonetaryAmount, _ := json.Marshal(dst.MonetaryAmount)
		if string(jsonMonetaryAmount) == "{}" { // empty struct
			dst.MonetaryAmount = nil
		} else {
			match++
		}
	} else {
		dst.MonetaryAmount = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.MonetaryAmount = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(PurchaseRevenueInUsd)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(PurchaseRevenueInUsd)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PurchaseRevenueInUsd) MarshalJSON() ([]byte, error) {
	if src.MonetaryAmount != nil {
		return json.Marshal(&src.MonetaryAmount)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PurchaseRevenueInUsd) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.MonetaryAmount != nil {
		return obj.MonetaryAmount
	}

	// all schemas are nil
	return nil
}

type NullablePurchaseRevenueInUsd struct {
	value *PurchaseRevenueInUsd
	isSet bool
}

func (v NullablePurchaseRevenueInUsd) Get() *PurchaseRevenueInUsd {
	return v.value
}

func (v *NullablePurchaseRevenueInUsd) Set(val *PurchaseRevenueInUsd) {
	v.value = val
	v.isSet = true
}

func (v NullablePurchaseRevenueInUsd) IsSet() bool {
	return v.isSet
}

func (v *NullablePurchaseRevenueInUsd) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurchaseRevenueInUsd(val *PurchaseRevenueInUsd) *NullablePurchaseRevenueInUsd {
	return &NullablePurchaseRevenueInUsd{value: val, isSet: true}
}

func (v NullablePurchaseRevenueInUsd) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurchaseRevenueInUsd) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


