/*
Developer API

Testing InvoiceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package v2

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/toshi1127/revenuecat-go/revenuecat"
)

func Test_revenuecat_InvoiceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InvoiceAPIService GetInvoice", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var customerId string
		var invoiceId string

		httpRes, err := apiClient.InvoiceAPI.GetInvoice(context.Background(), projectId, customerId, invoiceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvoiceAPIService ListCustomerInvoices", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var customerId string

		resp, httpRes, err := apiClient.InvoiceAPI.ListCustomerInvoices(context.Background(), projectId, customerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
