/*
Developer API

Testing AppAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package revenuecat

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/toshi1127/revenuecat-go/revenuecat"
)

func Test_revenuecat_AppAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AppAPIService CreateApp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.AppAPI.CreateApp(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppAPIService DeleteApp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var appId string

		resp, httpRes, err := apiClient.AppAPI.DeleteApp(context.Background(), projectId, appId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppAPIService GetApp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var appId string

		resp, httpRes, err := apiClient.AppAPI.GetApp(context.Background(), projectId, appId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppAPIService GetAppStorekitConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var appId string

		resp, httpRes, err := apiClient.AppAPI.GetAppStorekitConfig(context.Background(), projectId, appId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppAPIService ListAppPublicApiKeys", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var appId string

		resp, httpRes, err := apiClient.AppAPI.ListAppPublicApiKeys(context.Background(), projectId, appId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppAPIService ListApps", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.AppAPI.ListApps(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppAPIService UpdateApp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var appId string

		resp, httpRes, err := apiClient.AppAPI.UpdateApp(context.Background(), projectId, appId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
